name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-1'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
          terraform refresh
          IP=$(terraform output -raw instance_public_ip)
          echo "SERVER_IP=$IP" >> $GITHUB_ENV
        working-directory: ./terraform
        env:
          TF_VAR_public_key: ${{ secrets.EC2_PUBLIC_KEY }}

      - name: Update AWS Secrets Manager
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          JSON_SECRET=$(jq -n \
            --arg jpk "$JWT_PRIVATE_KEY" \
            --arg jpub "$JWT_PUBLIC_KEY" \
            --arg muri "$MONGO_URI" \
            '{JWT_PRIVATE_KEY: $jpk, JWT_PUBLIC_KEY: $jpub, MONGO_URI: $muri}')
          
          aws secretsmanager put-secret-value --secret-id devtinder/secrets --secret-string "$JSON_SECRET"

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/indumathi25/devtinder-backend:latest

      - name: Build and Push Chat Service
        uses: docker/build-push-action@v5
        with:
          context: ./chat-service
          push: true
          tags: ghcr.io/indumathi25/devtinder-chat-service:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/indumathi25/devtinder-frontend:latest

      - name: Wait for SSH to be ready
        run: |
          echo "Waiting for SSH to be ready on ${{ env.SERVER_IP }}..."
          for i in {1..20}; do
            if nc -zv -w 5 ${{ env.SERVER_IP }} 22; then
              echo "SSH is ready!"
              exit 0
            fi
            echo "SSH not ready yet, retrying in 10s... ($i/20)"
            sleep 10
          done
          echo "Error: SSH connection timed out after 200 seconds"
          exit 1

      - name: Deploy with Ansible
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          SERVER_IP: ${{ env.SERVER_IP }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "$EC2_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          export ANSIBLE_HOST_KEY_CHECKING=False
          echo "$SERVER_IP ansible_user=ubuntu ansible_ssh_private_key_file=deploy_key.pem" > inventory.ini
          
          ansible-playbook -i inventory.ini ansible/playbook.yml \
            -e "gh_user=${{ github.actor }}" \
            -e "gh_token=${{ secrets.GH_PAT }}"
